services:
    langchain_service:
        container_name: langchain_container
        image: langchain_image
        restart: on-failure
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            shm_size: 512m
        volumes:
            - ${HOME}/.cache/huggingface:/root/.cache/huggingface
            - ${HOME}/.cache/torch:/root/.cache/torch
        shm_size: 512m
        ports:
            - 8003:5000
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        entrypoint: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
